apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: loan-default
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: 'http://webhook-receiver:8080/prometheus'
        send_resolved: true