apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: loan-default
type: Opaque
data:
  aws-access-key-id: <YOUR_BASE64_ENCODED_ACCESS_KEY>
  aws-secret-access-key: <YOUR_BASE64_ENCODED_SECRET_KEY>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: loan-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: python:3.9-slim
        command: ["/bin/bash"]
        args: 
        - -c
        - |
          pip install mlflow[extras]==2.8.1 psycopg2-binary boto3
          mlflow server \
            --backend-store-uri postgresql://mlflow:mlflow123@postgres:5432/mlflow \
            --default-artifact-root s3://loan-mlops-mlflow-artifacts/artifacts \
            --host 0.0.0.0 \
            --port 5000
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: aws-secret-access-key
        - name: AWS_DEFAULT_REGION
          value: ap-south-1
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: loan-default
spec:
  selector:
    app: mlflow-server
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer