apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: loan-default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/rules/*.yml
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: [localhost:9090]
      - job_name: loan-model-metrics
        static_configs:
          - targets: [loan-model-api:8080]
        metrics_path: /metrics
        scrape_interval: 10s