apiVersion: v1
data:
  ab-testing-rules.yml: |
    groups:
    - name: ab_testing_performance
      interval: 30s
      rules:
      - alert: ModelPerformanceBelow65
        expr: loan_model_accuracy < 0.65
        for: 2m
        labels:
          severity: critical
          alert_type: performance_degradation
          trigger_github: "true"
        annotations:
          summary: "Test: Model performance threshold triggered"
          github_repo: "jayeshtulip/kaggle-data"
          github_workflow_file: "emergency-retrain.yml"
          github_ref: "main"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ab-testing-rules.yml":"groups:\n- name: ab_testing_performance\n  interval: 30s\n  rules:\n  - alert: ModelPerformanceBelow65\n    expr: model_accuracy{job=\"loan-model-metrics\"} \u003c 0.65\n    for: 2m\n    labels:\n      severity: critical\n      alert_type: performance_degradation\n      trigger_github: \"true\"\n    annotations:\n      summary: \"Test: Model performance threshold triggered\"\n      github_repo: \"jayeshtulip/kaggle-data\"\n      github_workflow_file: \"emergency-retrain.yml\"\n      github_ref: \"main\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-08-26T16:10:52Z","name":"prometheus-ab-alert-rules","namespace":"loan-default","resourceVersion":"3469074","uid":"a9e7bf23-4f3f-41b7-b933-b19e9fb4025b"}}
  creationTimestamp: "2025-08-26T16:10:52Z"
  name: prometheus-ab-alert-rules
  namespace: loan-default
  resourceVersion: "3518535"
  uid: a9e7bf23-4f3f-41b7-b933-b19e9fb4025b
