apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-ab-alert-rules
  namespace: loan-default
data:
  ab-testing-rules.yml: |
    groups:
    - name: ab_testing_performance
      interval: 30s
      rules:
      - alert: ModelPerformanceBelow65
        expr: loan_model_accuracy < 0.65
        for: 2m
        labels:
          severity: critical
          alert_type: performance_degradation
          trigger_github: "true"
          github_workflow: "emergency-model-retrain"
        annotations:
          summary: "Model performance below 65%: {{ $value | humanizePercentage }}"
          description: "Model accuracy dropped to {{ $value | humanizePercentage }}, triggering retraining workflow"
          github_repo: "your-username/your-repo-name"
          github_workflow_file: "emergency-retrain.yml"
          github_ref: "main"